### ISSUE TITLE
php 8.3 deprecation

### ISSUE THREAD

**Issue by 8ctopus** [swew-app/cli#2]
Hello, I just started experimenting with your package and it looks great so far.

```txt
$ php demo.php show:time
PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in ...\vendor\swew\cli\src\Command\CommandArgument.php on line 196
```

https://github.com/swew-app/cli/blob/f01b44b6b3458e1661b4add5b31c93654ed4b60f/src/Command/CommandArgument.php#L191-L200

**Comment by avil13** [comment]
Thank you.
